dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
node_js:
  - "node"
script:
  - npm run ci:test
  #- npm run e2e
deploy: &heroku
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key: $HEROKU_API_KEY
