dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
node_js:
  - "node"
script:
  - npm run ci:test
  - npm run ci:e2e
  - npm run build:prod
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GAME_OF_LIFE_GITHUB_TOKEN
    keep-history: true
    local-dir: dist
    verbose: true
    on:
        branch: master
